// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    MusicList: typeof import('./src/components/musicList.vue')['default']
    SearchMusic: typeof import('./src/components/searchMusic.vue')['default']
  }
}
